// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package animal

// Injectors from wire.go:

func InitializeDog() Dog {
	name := NewName()
	dog := NewDog(name)
	return dog
}
