// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package signup

import (
	"github.com/kyohei0423/go-practice/clean-architecture/interface/repository"
	"github.com/kyohei0423/go-practice/clean-architecture/usecase"
)

// Injectors from wire.go:

func InitializeInteractor() usecase.ISignupUsecase {
	iUserRepository := repository.NewUser()
	iSignupUsecase := usecase.NewSignupInteractor(iUserRepository)
	return iSignupUsecase
}
